# Generated by Django 5.1.5 on 2026-04-15 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('color', models.CharField(choices=[('clay', 'Clay'), ('lavender', 'Lavender'), ('mint', 'Mint'), ('sage', 'Sage'), ('ochre', 'Ochre')], max_length=20)),
            ],
        ),
    ]
